src/main/java/kr/or/sw/controller/AuthController.java
src/main/java/kr/or/sw/mapper/AuthDAO.java
src/main/java/kr/or/sw/model/EmpDTO.java
src/main/java/kr/or/sw/model/UsrDTO.java
src/main/java/kr/or/sw/service/AuthServiceImpl.java
src/main/resources/mybatis/mapper/AuthMapper.xml
src/main/webapp/css/login.css

Add Logout

---

src/main/java/kr/or/sw/util/CipherUtil.java

Add Password Encryption

---

src/main/java/kr/or/sw/controller/AuthController.java
src/main/java/kr/or/sw/model/MemberDTO.java
src/main/java/kr/or/sw/service/AuthService.java
src/main/java/kr/or/sw/service/AuthServiceImpl.java
src/main/resources/mybatis/mapper/authMapper.xml
src/main/webapp/css/register.scss
src/main/webapp/js/register.js
src/main/webapp/register.html

add member insert and fix register page(add question and answer input and fix css to align information inputs)

feat(add member insert):

---

src/main/webapp/WEB-INF/views/register.html
src/main/webapp/css/register.css
src/main/webapp/css/register.scss
src/main/webapp/js/register.js

validation for email, password, password-confirm and contact
also added css effect for validations.

feat(add validation for register form and etc details): 

---

src/main/webapp/css/main.css
src/main/webapp/css/main.scss
src/main/webapp/main.jsp

main.jsp main admin page design prototype

feat(main)

---

.gitignore
src/main/webapp/css/index.css
src/main/webapp/css/index.scss
src/main/webapp/docs/passwordSearch1.html
src/main/webapp/docs/passwordSearch2.html

fix(index): fix index

---

src/main/java/kr/or/sw/controller/AuthController.java
src/main/java/kr/or/sw/controller/MemberController.java
src/main/java/kr/or/sw/mapper/SearchDAO.java
src/main/java/kr/or/sw/mapper/SearchDAOImpl.java
src/main/java/kr/or/sw/service/SearchService.java
src/main/java/kr/or/sw/service/SearchServiceImpl.java
src/main/resources/mybatis/mapper/searchMapper.xml
src/main/webapp/WEB-INF/views/search.jsp
src/main/webapp/css/index.css
src/main/webapp/css/search.css
src/main/webapp/js/memberSearch.js
src/main/webapp/js/register.js
src/main/webapp/js/side.js

add search by keyword.
and fix search page's paging and data view for search by keyword. also fix register page's contact validation. now contact must contain '-'.
fix encoding character set in register request

feat(add search by keyword):

---

pom.xml
src/main/java/kr/or/sw/controller/AuthController.java
src/main/java/kr/or/sw/controller/MemberController.java
src/main/resources/mybatis/mapper/searchMapper.xml
src/main/resources/sql/member.sql
src/main/webapp/WEB-INF/views/side.jsp
src/main/webapp/index.html

- Controller init()
- Correct index.html resources path
- Add PL/SQL Loop

refactor: Minor Update

---

pom.xml
src/main/java/kr/or/sw/controller/AuthController.java
src/main/java/kr/or/sw/controller/HomeController.java
src/main/java/kr/or/sw/controller/MemberController.java
src/main/java/kr/or/sw/service/SearchService.java
src/main/java/kr/or/sw/service/SearchServiceImpl.java

- Enhanced Switch
- Refactor Search

build(JDK): Version Up to JDK 17 LTS

---

.gitignore
src/main/java/kr/or/sw/mapper/AuthDAOImpl.java
src/main/java/kr/or/sw/mapper/SearchDAOImpl.java
src/main/java/kr/or/sw/service/AuthServiceImpl.java
src/main/java/kr/or/sw/service/SearchServiceImpl.java
src/main/java/kr/or/sw/util/CipherUtil.java
src/main/java/kr/or/sw/util/MyBatisUtil.java
src/main/resources/mybatis/mapper/authMapper.xml
src/main/resources/mybatis/mapper/searchMapper.xml

- Thread-safe using Initialization-on-demand holder idiom
- Return resource with using try-with-resource

refactor: Thread-safe & Try-with-resource

---

src/main/webapp/indexManager.html
src/main/webapp/stockManage.jsp

- index.html fixed
- indexManager added
- stockManage added

add(stockManage,indexManager)

---

src/main/java/kr/or/sw/mapper/MemberDAO.java
src/main/java/kr/or/sw/mapper/MemberDAOImpl.java
src/main/java/kr/or/sw/model/EmpDTO.java
src/main/java/kr/or/sw/model/MemberDTO.java
src/main/java/kr/or/sw/service/AuthServiceImpl.java
src/main/java/kr/or/sw/service/MemberServiceImpl.java
src/main/resources/mybatis/mapper/authMapper.xml
src/main/resources/mybatis/mapper/memberMapper.xml
src/main/resources/sql/member.sql
src/main/webapp/WEB-INF/views/auth/register.html
src/main/webapp/WEB-INF/views/member/member.jsp
src/main/webapp/WEB-INF/views/member/update.jsp
src/main/webapp/index.html
src/main/webapp/indexManager.html
src/main/webapp/stockManage.jsp

fix(DB): Change Field Name

---

src/main/webapp/css/stockManage.css
src/main/webapp/css/stockManage.scss
src/main/webapp/index.html
src/main/webapp/js/passwordSearch1.js
src/main/webapp/stockManage.jsp

fix(stockManage.css, stockManage.jsp)

---

src/main/java/kr/or/sw/controller/AuthController.java
src/main/java/kr/or/sw/controller/HomeController.java
src/main/java/kr/or/sw/controller/MemberController.java
src/main/java/kr/or/sw/controller/ProductController.java
src/main/java/kr/or/sw/controller/StockController.java
src/main/java/kr/or/sw/mapper/ProductDAO.java
src/main/java/kr/or/sw/mapper/ProductDAOImpl.java
src/main/java/kr/or/sw/mapper/StockDAO.java
src/main/java/kr/or/sw/mapper/StockDAOImpl.java
src/main/java/kr/or/sw/service/ProductService.java
src/main/java/kr/or/sw/service/ProductServiceImpl.java
src/main/java/kr/or/sw/service/StockService.java
src/main/java/kr/or/sw/service/StockServiceImpl.java
src/main/resources/mybatis/mapper/productMapper.xml
src/main/resources/mybatis/mapper/stockMapper.xml
src/main/resources/mybatis/mybatis-config.xml

Add Controller, Service, DAO, Mapper

---

src/main/java/kr/or/sw/controller/AuthController.java
src/main/java/kr/or/sw/controller/HomeController.java
src/main/java/kr/or/sw/controller/MemberController.java
src/main/java/kr/or/sw/controller/ProductController.java
src/main/java/kr/or/sw/controller/StockController.java
src/main/java/kr/or/sw/service/AuthService.java
src/main/java/kr/or/sw/service/AuthServiceImpl.java
src/main/java/kr/or/sw/service/MemberService.java
src/main/java/kr/or/sw/service/MemberServiceImpl.java
src/main/java/kr/or/sw/service/ProductService.java
src/main/java/kr/or/sw/service/ProductServiceImpl.java
src/main/java/kr/or/sw/service/Service.java
src/main/java/kr/or/sw/service/StockService.java
src/main/java/kr/or/sw/service/StockServiceImpl.java

refactor(Service)

---

src/main/webapp/css/passwordSearch.css
src/main/webapp/css/passwordSearch.scss
src/main/webapp/css/passwordSearch2.css
src/main/webapp/docs/passwordSearch1.html
src/main/webapp/docs/passwordSearch2.html
src/main/webapp/index.html
src/main/webapp/js/index.js

- index update detail
- index.js bug fixed

fix(index.css, passwordSearch.css, index.js)

---

src/main/webapp/css/info.css
src/main/webapp/css/info.scss
src/main/webapp/info.jsp

- add client main page (menu and info)

feat(style): add client main page

---

src/main/java/kr/or/sw/controller/AuthController.java
src/main/java/kr/or/sw/controller/HomeController.java
src/main/java/kr/or/sw/controller/MemberController.java
src/main/java/kr/or/sw/controller/ProductController.java
src/main/java/kr/or/sw/controller/StockController.java
src/main/java/kr/or/sw/service/ProductServiceImpl.java
src/main/webapp/WEB-INF/views/customer.jsp
src/main/webapp/WEB-INF/views/layouts/side.jsp
src/main/webapp/WEB-INF/views/main.jsp
src/main/webapp/WEB-INF/views/product/productInsert.jsp
src/main/webapp/WEB-INF/views/product/productOrder.jsp
src/main/webapp/WEB-INF/views/stock/stock.jsp

chore(main)

---

src/main/webapp/WEB-INF/views/layouts/side.jsp
src/main/webapp/WEB-INF/views/product/productInsert.jsp
src/main/webapp/css/insert.css
src/main/webapp/css/insert.scss
src/main/webapp/js/productInsert.js

now we can see preview image when upload file in product insert page.
also add form and submit button in product insert page.

feat: add preview image in product insert page

---

src/main/java/kr/or/sw/controller/ProductController.java
src/main/java/kr/or/sw/mapper/AuthDAO.java
src/main/java/kr/or/sw/mapper/AuthDAOImpl.java
src/main/java/kr/or/sw/mapper/MemberDAO.java
src/main/java/kr/or/sw/mapper/MemberDAOImpl.java
src/main/java/kr/or/sw/mapper/ProductDAO.java
src/main/java/kr/or/sw/mapper/ProductDAOImpl.java
src/main/java/kr/or/sw/model/ProductDTO.java
src/main/java/kr/or/sw/model/ProductImgDTO.java
src/main/java/kr/or/sw/service/AuthServiceImpl.java
src/main/java/kr/or/sw/service/MemberServiceImpl.java
src/main/java/kr/or/sw/service/ProductServiceImpl.java
src/main/java/kr/or/sw/service/Service.java

refactor(dao): increase cohesion

---

src/main/java/kr/or/sw/service/StockServiceImpl.java
src/main/resources/mybatis/mapper/stockMapper.xml

fix(stockMapper)

---

src/main/java/kr/or/sw/controller/StockController.java
src/main/java/kr/or/sw/mapper/StockDAO.java
src/main/java/kr/or/sw/mapper/StockDAOImpl.java
src/main/java/kr/or/sw/model/StockDTO.java
src/main/java/kr/or/sw/service/StockServiceImpl.java
src/main/resources/mybatis/mapper/stockMapper.xml
src/main/webapp/WEB-INF/views/layouts/side.jsp
src/main/webapp/WEB-INF/views/stock/stockList.jsp
src/main/webapp/WEB-INF/views/stock/stockUpdate.jsp
src/main/webapp/js/stock.js

- stockUpdate.jsp
- StockServiceImpl
- stockMapper

add(stock update, delete)

---

src/main/webapp/WEB-INF/views/customer.jsp
src/main/webapp/WEB-INF/views/product/productInsert.jsp
src/main/webapp/js/customer.js

add divide by category.
add search.
search use Trie data structure,
insert all continuous substring for i from 0 to string's length N, [i,N-1] into trie for search all substring in product's name.
first time, I used Aho-Corasick. but as I have thought of this situation, don't need Aho-Corasick. we can do it just use Trie.

feat: enhance customer page

---

src/main/java/kr/or/sw/controller/StockController.java
src/main/java/kr/or/sw/mapper/StockDAO.java
src/main/java/kr/or/sw/mapper/StockDAOImpl.java
src/main/java/kr/or/sw/model/StockDTO.java
src/main/java/kr/or/sw/service/StockServiceImpl.java
src/main/resources/mybatis/mapper/stockMapper.xml
src/main/webapp/WEB-INF/views/stock/stockInsert.jsp
src/main/webapp/js/index.js

fix (index.js)

---

src/main/resources/mybatis/mapper/customerMapper.xml
src/main/webapp/WEB-INF/views/customer.jsp
src/main/webapp/css/customer.css
src/main/webapp/css/customer.scss
src/main/webapp/js/customer.js

all data, category data, search data union to menu's idx

fix: fix shopping cart

---

pom.xml
src/main/java/kr/or/sw/controller/ProductController.java
src/main/java/kr/or/sw/controller/StockController.java
src/main/java/kr/or/sw/mapper/ProductDAO.java
src/main/java/kr/or/sw/mapper/ProductDAOImpl.java
src/main/java/kr/or/sw/mapper/StockDAO.java
src/main/java/kr/or/sw/mapper/StockDAOImpl.java
src/main/java/kr/or/sw/model/ProductDTO.java
src/main/java/kr/or/sw/model/ProductImgDTO.java
src/main/java/kr/or/sw/model/StockDTO.java
src/main/java/kr/or/sw/service/ProductServiceImpl.java
src/main/java/kr/or/sw/service/StockServiceImpl.java
src/main/resources/mybatis/mapper/productMapper.xml
src/main/resources/mybatis/mapper/stockMapper.xml
src/main/webapp/WEB-INF/views/customer.jsp
src/main/webapp/WEB-INF/views/product/productInsert.jsp
src/main/webapp/css/customer.scss
src/main/webapp/js/customer.js

- update product and previously uploaded image

feat(product): update product

---

src/main/java/kr/or/sw/controller/CustomerController.java
src/main/java/kr/or/sw/mapper/CustomerDAO.java
src/main/java/kr/or/sw/mapper/CustomerDAOImpl.java
src/main/java/kr/or/sw/service/AuthServiceImpl.java
src/main/java/kr/or/sw/service/CustomerService.java
src/main/java/kr/or/sw/service/CustomerServiceImpl.java
src/main/java/kr/or/sw/service/StockServiceImpl.java
src/main/resources/mybatis/mapper/customerMapper.xml
src/main/resources/mybatis/mybatis-config.xml
src/main/webapp/WEB-INF/views/product/productUpdate.jsp
src/main/webapp/css/main.scss
src/main/webapp/css/order.scss
src/main/webapp/js/customer.js
src/main/webapp/js/productInsert.js

refactor(customer)

---

src/main/java/kr/or/sw/controller/AuthController.java
src/main/java/kr/or/sw/controller/CustomerController.java
src/main/resources/mybatis/mapper/authMapper.xml
src/main/resources/mybatis/mapper/balanceMapper.xml
src/main/webapp/WEB-INF/views/customer.jsp
src/main/webapp/js/customer.js

now send ajax's response data.
and add balanceMapper's namespace.

fix: fix makeorder

---

src/main/java/kr/or/sw/controller/ProductController.java
src/main/java/kr/or/sw/mapper/ProductDAO.java
src/main/java/kr/or/sw/mapper/ProductDAOImpl.java
src/main/java/kr/or/sw/service/ProductService.java
src/main/java/kr/or/sw/service/ProductServiceImpl.java
src/main/resources/mybatis/mapper/productMapper.xml

refactor(product)

---

src/main/java/kr/or/sw/mapper/ProductDAO.java
src/main/java/kr/or/sw/mapper/ProductDAOImpl.java
src/main/java/kr/or/sw/model/StockDTO.java
src/main/java/kr/or/sw/service/StockServiceImpl.java
src/main/resources/mybatis/mapper/productMapper.xml
src/main/webapp/WEB-INF/views/product/productList.jsp
src/main/webapp/js/productIngredient.js

and fix StockDTO refer to stock table.

feat: add get already selected recipe data of product.

---

src/main/java/kr/or/sw/mapper/MemberDAO.java
src/main/java/kr/or/sw/mapper/MemberDAOImpl.java
src/main/java/kr/or/sw/service/CustomerServiceImpl.java
src/main/resources/mybatis/mapper/memberMapper.xml
src/main/webapp/WEB-INF/views/customer.jsp
src/main/webapp/js/customer.js

feat: done update customer's self

---

src/main/java/kr/or/sw/mapper/CustomerDAOImpl.java
src/main/java/kr/or/sw/mapper/ProductDAOImpl.java
src/main/java/kr/or/sw/service/ProductServiceImpl.java
src/main/resources/mybatis/mapper/productMapper.xml

feat(product): update recipe

---

src/main/resources/mybatis/mapper/customerMapper.xml

feat(product): decrease stock

---

src/main/resources/mybatis/mapper/customerMapper.xml
src/main/resources/mybatis/mapper/stockMapper.xml

hot-fix: add SQL hint

---

src/main/webapp/WEB-INF/views/balance/balance.jsp

add(balance list format, color)

---

src/main/webapp/css/customer.css
src/main/webapp/css/customer.scss
src/main/webapp/js/customer.js

now user never insert any input in shopping product count.

fix: product amount change tag type div from input

---

src/main/webapp/css/product.css
src/main/webapp/css/product.scss
src/main/webapp/js/productIngredient.js

js default sort is "alphabetical".
so, when data is [1, 2, 3, 4, 8, 10, 11, 12, 13, 20, 22].
sorted result is [1, 10, 11, 12, 13, 2, 20, 22, 3, 4, 8]
changed sort's comparator.

fix add ingredient of product page

---

src/main/java/kr/or/sw/controller/AuthController.java
src/main/java/kr/or/sw/service/AuthService.java
src/main/java/kr/or/sw/service/AuthServiceImpl.java
src/main/java/kr/or/sw/service/CustomerServiceImpl.java
src/main/java/kr/or/sw/service/ProductServiceImpl.java
src/main/java/kr/or/sw/service/StockServiceImpl.java
src/main/resources/mybatis/mapper/authMapper.xml
src/main/resources/mybatis/mapper/customerMapper.xml
src/main/webapp/js/findPassword.js

- add hashing answer when register as a new member

feat(auth): hash answer

---

src/main/java/kr/or/sw/model/BalanceVO.java
src/main/resources/mybatis/mapper/balanceMapper.xml

fix(balance): get accumulated fields

---

src/main/webapp/WEB-INF/views/balance/balance.jsp
src/main/webapp/WEB-INF/views/member/member.jsp
src/main/webapp/WEB-INF/views/product/productList.jsp
src/main/webapp/WEB-INF/views/stock/stockList.jsp

when list size is multiplied by 10, foreach's end value error fix.

fix: fix paging
